:set hlsearch
:set nu
:set rnu
:syntax on
:set softtabstop=4
:set tabstop=4
:set shiftwidth=4
:set clipboard=unnamedplus
:set listchars=tab:>-,trail:·,precedes:<,extends:>,eol:$
:nmap <C-A> :set invlist <Enter>
